# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         YAML-YuyuPress
version:      0.07_1
version_from: lib/YAML/YuyuPress.pm
installdirs:  site
requires:
    HTTP::Server::Simple::CGI:     0.02
    Object::props:                 0
    Template:                      2.14
    Test::More:                    0
    YAML:                          0.36

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
