#!/usr/bin/perl

use lib "../lib";

my $yaml = shift || die 'Andestá el argumento?';
my $path = shift || '..';
my $plantilla = shift || 'normal.tmpl';

use YAML::YuyuPress;
my $pwd = `pwd`;
chomp( $pwd );

my $yuyu = YAML::YuyuPress->new( path => $path, 
				 plantilla => $plantilla, 
				 contenido => $yaml,
				 staticdir => $pwd );
$yuyu->port(9000);
$yuyu->run();
